import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../baka-helper.user.js',import.meta.url),'utf8').replace('  if(document.readyState===\'loading\')','  window.__BANK={bankQuestion,bankParseQuestion,bankKey,bankLookup,bankEntries,collectBank,bankExport,bankImport,bankBeforeAdvance,explicitCorrect,startBankScan,stopBankScan,bankScanTick,restoreBankScan};\n  if(document.readyState===\'loading\')');
const hook=`window.__T={S,cfg,providers,profile,parseQuestion,questionRoots,filled,checked,validateAnswer,fill,answer,makeRequest,decode,taskDone,advance,firstUnfinished,pageKey,chapterId,currentEpoch,tick,readTick,readIdentity,pause,start,doHomework,mount,models,readerLinks,handleSubmission,ui,supportsVision,setFullAuto,responseTimeout,cardIdentity,deferQuestion,recoveryIO,readRecovery,recoverPage,recoveryBoot,recoveryTick,recoveryContext,pageError,safeCourseURL,rememberReturn,videoWatchdog,playVideo,loadQuestionFonts,captureStage,fault,progress,readFlow,flowBoot,continuityTick,recoverContinuous,flowURL,readerNext,readerScroller,waitReader,acquire,ownsLease,renewLease,release,leavePage,restorePage,loginForm,saveLoginAccount,clearLoginAccount,loginTick,authTick,readAuth,rememberSession,makeAuthRequest,suspendForAuth,cancelAuthResume,mountLogin,redact};return;\n`;
async function setup({titleOnly=false,video=false,complete=false,moreVideos=false,quiz=false,reader=false,overview=false,login=false,ownerId="test-tab"}={}){
  const dom=new JSDOM(reader?`<body><div id="ztMainBoxFocus"></div><p>阅读正文</p><a class="nodeItem" href="?courseId=book&knowledgeId=second">下一页</a></body>`:`<body><div id="mainid"></div><div id="dct1" class="active" title="${quiz?'章节测验':video?'视频':''}" cardid="one"></div><div id="dct2" title="章节测验" cardid="two"></div>${titleOnly?'':'<iframe id="iframe"></iframe>'}<div id="content1"><div id="cur100" class="posCatalog_active"><span class="posCatalog_name" onclick="" title="当前">当前</span></div><div id="cur101"><span class="posCatalog_name" onclick="" title="已完成">已完成</span><span class="icon_Completed"></span></div><div id="cur102"><span class="posCatalog_name" onclick="" title="未完成">未完成</span><span class="orangeNew">2</span></div></div></body>`,{url:reader?'https://mooc1.chaoxing.com/mooc-ans/ztnodedetailcontroller/visitnodedetail?courseId=book&knowledgeId=first':'https://mooc1.chaoxing.com/mycourse/studentstudy?courseId=course&chapterId=100',runScripts:'outside-only',pretendToBeVisual:true});
  if(overview)dom.reconfigure({url:'https://mooc2-ans.chaoxing.com/mooc2-ans/mycourse/stu?courseid=course'});
  if(login){dom.reconfigure({url:"https://v8.chaoxing.com/"});dom.window.document.body.innerHTML='<form id="loginForm" method="post"><input id="uunnmm" name="uname" type="text"><input id="pwd" name="pwd" type="password"><input id="login" type="button" value="登录"></form><div id="captcha" hidden>请完成安全验证 向右拖动滑块填充拼图</div>';}
  const w=dom.window,store=new Map();w.unsafeWindow=w;
  w.GM_getValue=(k,d)=>store.has(k)?store.get(k):d;w.GM_setValue=(k,v)=>store.set(k,v);
  w.GM_getTab=fn=>fn({cirnoId:ownerId});w.GM_saveTab=()=>{};w.GM_openInTab=()=>{};
  w.GM_xmlhttpRequest=()=>{throw Error('Unexpected API call');};w.setInterval=()=>0;
  function visible(d){d.defaultView.HTMLElement.prototype.getClientRects=function(){let el=this;while(el){if(el.hidden||el.style?.display==='none')return [];el=el.parentElement;}return [{}];};}
  visible(w.document);let plays=0,clicks=[];
  const f=w.document.querySelector('#iframe');
  if(f){
    Object.defineProperty(f,'src',{get:()=>`https://mooc1.chaoxing.com/mooc-ans/knowledge/cards?courseid=course&knowledgeid=100&num=0`});
    f.contentDocument.body.innerHTML='<div id="pageDiv"></div>';Object.defineProperty(f.contentDocument,'readyState',{get:()=> 'complete'});visible(f.contentDocument);
    if(video){
      f.contentDocument.querySelector('#pageDiv').innerHTML=`<div class="ans-attach-ct ${complete?'ans-job-finished':''}"><div class="ans-job-icon ans-job-video" aria-label="任务点${complete?'已':'未'}完成"></div><iframe src="/ananas/modules/video/index.html"></iframe></div>`+(moreVideos?'<div class="ans-attach-ct"><div class="ans-job-icon ans-job-video" aria-label="任务点未完成"></div><iframe src="/ananas/modules/video/index.html"></iframe></div>':'');
      for(const vf of f.contentDocument.querySelectorAll('iframe')){
        vf.contentDocument.open();vf.contentDocument.write('<!doctype html><html><body><video></video></body></html>');vf.contentDocument.close();Object.defineProperty(vf.contentDocument,'readyState',{get:()=> 'complete'});visible(vf.contentDocument);
        const v=vf.contentDocument.querySelector('video');v.play=async()=>{plays++;};v.pause=()=>{};
      }
    }
  }
  for(const el of w.document.querySelectorAll('.posCatalog_name,[id^="dct"],a.nodeItem'))el.addEventListener('click',e=>{e.preventDefault();clicks.push(el.closest('[id^="cur"]')?.id||el.id||'next');});
  const injection=source.replace("  if(document.readyState==='loading')",hook+"  if(document.readyState==='loading')");
  await w.eval(injection);const T=w.__T;T.S.started=true;T.S.key=T.pageKey();T.S.changed=Date.now()-30000;store.set('cirno.lock.v5',{owner:ownerId,at:Date.now()});
  return {w,T,store,card:f?.contentDocument,counts:()=>({plays,clicks}),close:()=>w.close(),visible};
}
function question(d,{multi=false,encrypted=false,filled=false}={}){
  const root=d.createElement('div');root.className='TiMu';root.innerHTML=`<div class="Zy_TItle"><div class="fontLabel ${encrypted?'font-cxsecret':''}">【${multi?'多':'单'}选题】测试题</div></div><ul class="Zy_ulTop">${['A','B','C'].map(l=>`<li role="${multi?'checkbox':'radio'}" qid="100"><span class="num_option ${filled&&l==='A'?'check_answer':''}" data="${l}">${l}</span><a>选项 ${l}</a></li>`).join('')}</ul><input type="hidden" id="answer100" value="${filled?'A':''}">`;d.body.append(root);
  root.querySelectorAll('li').forEach(li=>li.onclick=()=>{const s=li.querySelector('span');if(!multi)root.querySelectorAll('.num_option').forEach(x=>x.classList.remove('check_answer'));s.classList.toggle('check_answer');root.querySelector('input').value=[...root.querySelectorAll('.check_answer')].map(x=>x.getAttribute('data')).join('');});
  return root;
}
let passed=0;
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
await test('title-only chapter without iframe or next button advances',async()=>{const x=await setup({titleOnly:true});await x.T.tick();assert.deepEqual(x.counts().clicks,['cur102']);x.close();});
await test('empty loaded card no longer stalls',async()=>{const x=await setup();await x.T.tick();assert.deepEqual(x.counts().clicks,['cur102']);x.close();});
await test('unfinished video plays and never advances',async()=>{const x=await setup({video:true});await x.T.tick();assert.equal(x.counts().plays,1);assert.equal(x.counts().clicks.length,0);x.close();});
await test('completed video skipped; completed chapter bypassed',async()=>{const x=await setup({video:true,complete:true});await x.T.tick();assert.equal(x.counts().plays,0);assert.deepEqual(x.counts().clicks,['cur102']);x.close();});
await test('multiple videos waits for remaining video',async()=>{const x=await setup({video:true,complete:true,moreVideos:true});await x.T.tick();assert.equal(x.counts().plays,1);assert.equal(x.counts().clicks.length,0);x.close();});
await test('homework option keeps quiz card in route',async()=>{const x=await setup({video:true,complete:true});x.T.cfg.homework=true;await x.T.tick();assert.deepEqual(x.counts().clicks,['dct2']);x.close();});
await test('navigation does not double-click before load',async()=>{const x=await setup();await x.T.tick();await x.T.tick();assert.equal(x.counts().clicks.length,1);x.close();});
await test('navigation timeout pauses',async()=>{const x=await setup();x.T.advance();x.T.S.pending.at=Date.now()-26000;await x.T.tick();assert.equal(x.T.S.started,false);x.close();});
await test('hidden completion tooltip is not finished',async()=>{const x=await setup({video:true});const m=x.card.querySelector('.ans-job-icon');m.innerHTML='<div style="display:none">完成条件</div>';assert.equal(x.T.taskDone(m),false);x.close();});
await test('wrong tab lock stops automation',async()=>{const x=await setup({video:true});x.store.set('cirno.lock.v5',{owner:'different',at:Date.now()});await x.T.tick();assert.equal(x.T.S.started,false);assert.equal(x.counts().plays,0);x.close();});
await test('encrypted text activates image mode',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card,{encrypted:true}));assert.equal(q.visual,true);assert.equal(q.options.length,3);x.close();});
await test('existing answers are preserved',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card,{filled:true}));assert.equal(x.T.filled(q),true);x.close();});
await test('custom Chaoxing option controls receive validated answers',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card));await x.T.fill(q,{choices:['B'],blanks:[],answer:''},x.T.currentEpoch());assert.equal(q.root.querySelector('input').value,'B');x.close();});
await test('multiselect clears old options and selects exact set',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card,{multi:true,filled:true}));await x.T.fill(q,{choices:['B','C'],blanks:[],answer:''},x.T.currentEpoch());assert.equal(q.root.querySelector('input').value,'BC');x.close();});
await test('invalid labels cannot mutate options',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card));await assert.rejects(x.T.fill(q,{choices:['Z'],blanks:[],answer:''},x.T.currentEpoch()));assert.equal(q.root.querySelector('input').value,'');x.close();});
await test('stale response cannot fill new page',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card));const ctx=x.T.currentEpoch();x.T.S.epoch++;await assert.rejects(x.T.fill(q,{choices:['A'],blanks:[],answer:''},ctx));assert.equal(q.root.querySelector('input').value,'');x.close();});
await test('fill blank fields and dispatch input events',async()=>{const x=await setup();const r=x.card.createElement('div');r.innerHTML='<div class="Zy_TItle">【填空题】填两个空</div><input type="text"><input type="text">';x.card.body.append(r);let events=0;r.addEventListener('input',()=>events++);const q=x.T.parseQuestion(r);await x.T.fill(q,{choices:[],blanks:['一','二'],answer:''},x.T.currentEpoch());assert.equal(events,2);assert(x.T.filled(q));x.close();});
await test('auto-submit off leaves filled work unsubmitted',async()=>{const x=await setup({quiz:true});question(x.card,{filled:true});const b=x.card.createElement('button');b.textContent='提交';b.className='btnSubmit';let submits=0;b.onclick=()=>submits++;x.card.body.append(b);x.T.cfg.homework=true;x.T.cfg.autoSubmit=false;await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(submits,0);assert.equal(x.T.S.started,false);x.close();});
await test('auto-submit on sends exactly one submission',async()=>{const x=await setup({quiz:true});question(x.card,{filled:true});const b=x.card.createElement('button');b.textContent='提交';b.className='btnSubmit';let submits=0;b.onclick=()=>submits++;x.card.body.append(b);x.T.cfg.homework=true;x.T.cfg.autoSubmit=true;await x.T.doHomework(x.card,x.T.currentEpoch());await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(submits,1);x.close();});
await test('reader scrolls before clicking next',async()=>{const x=await setup({reader:true});const s=x.w.document.documentElement;Object.defineProperty(x.w.document,'scrollingElement',{value:s});Object.defineProperty(s,'scrollHeight',{value:3000});s.scrollTop=0;let scrolled=0;x.w.scrollBy=()=>scrolled++;await x.T.readTick();assert.equal(scrolled,1);assert.equal(x.counts().clicks.length,0);x.close();});
await test('reader waits at bottom before advancing and stores completed page',async()=>{const x=await setup({reader:true});const s=x.w.document.documentElement;Object.defineProperty(x.w.document,'scrollingElement',{value:s});Object.defineProperty(s,'scrollHeight',{value:500});x.T.S.readerSignature=x.T.readIdentity();x.T.S.readerSince=Date.now()-30000;x.T.S.readerBottom=Date.now()-2000;await x.T.readTick();assert.deepEqual(x.counts().clicks,['next']);assert(x.store.get('cirno.read.book').includes('first'));x.close();});
await test('five provider protocols include images without key in URL',async()=>{const x=await setup();for(const p0 of Object.values(x.T.providers).filter(p=>p.base)){const p={...p0,key:'secret'};const req=x.T.makeRequest(p,{question:'测试'},'data:image/png;base64,AAAA');assert(!req.url.includes('secret'));assert(JSON.stringify(req.body).includes('AAAA'));assert(Object.values(req.headers).some(v=>v.includes('secret')));}x.close();});
await test('truncated and uncertain provider outputs never become answers',async()=>{const x=await setup();assert.throws(()=>x.T.decode({kind:'chat'},{choices:[{finish_reason:'length',message:{content:'{}'}}]}));assert.throws(()=>x.T.decode({kind:'gemini'},{candidates:[{finishReason:'MAX_TOKENS'}]}));assert.throws(()=>x.T.decode({kind:'claude'},{stop_reason:'max_tokens'}));x.close();});
await test('all five provider output envelopes decode to same answer',async()=>{const x=await setup();const a={choices:['A'],blanks:[],answer:'A',explanation:'x',uncertain:false},raw=JSON.stringify(a);const cases=[['responses',{status:'completed',output:[{content:[{type:'output_text',text:raw}]}]}],['gemini',{candidates:[{finishReason:'STOP',content:{parts:[{text:raw}]}}]}],['claude',{stop_reason:'end_turn',content:[{type:'text',text:raw}]}],['chat',{choices:[{finish_reason:'stop',message:{content:raw}}]}]];for(const [kind,data]of cases)assert.equal(x.T.decode({kind},data).answer,'A');x.close();});
await test('pause stops parent reader ticket',async()=>{const x=await setup();x.store.set('cirno.reader.v5',{id:'r',parent:'test-tab',reader:'reader-tab',state:'active'});x.T.S.waitReader={id:'r'};x.T.pause();assert.equal(x.store.get('cirno.reader.v5').state,'stopped');assert.equal(x.T.S.waitReader,null);x.close();});
await test('reader honors stop sent by parent',async()=>{const x=await setup({reader:true});x.T.S.reading={id:'r'};x.store.set('cirno.reader.v5',{id:'r',state:'stopped'});await x.T.readTick();assert.equal(x.T.S.started,false);assert.equal(x.counts().clicks.length,0);x.close();});
await test('previously read chapter skips dwell',async()=>{const x=await setup({reader:true});x.store.set('cirno.read.book',['first']);await x.T.readTick();assert.deepEqual(x.counts().clicks,['next']);x.close();});
await test('completed homework wrapper never resubmits visible form',async()=>{const x=await setup({quiz:true});x.card.querySelector('#pageDiv').innerHTML='<div class="ans-attach-ct ans-job-finished"><span class="ans-job-icon" aria-label="任务点已完成"></span><iframe src="/ananas/modules/work/index.html"></iframe></div>';const f=x.card.querySelector('#pageDiv iframe');f.contentDocument.open();f.contentDocument.write('<body></body>');f.contentDocument.close();Object.defineProperty(f.contentDocument,'readyState',{get:()=> 'complete'});x.visible(f.contentDocument);question(f.contentDocument,{filled:true});const b=f.contentDocument.createElement('button');b.className='btnSubmit';b.textContent='提交';let submits=0;b.onclick=()=>submits++;f.contentDocument.body.append(b);x.T.cfg.homework=true;x.T.cfg.autoSubmit=true;await x.T.tick();assert.equal(submits,0);assert.equal(x.counts().clicks.length,1);x.close();});
await test('late API response after cancel cannot populate answer cache',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card));x.T.cfg.profiles.openai={key:'fake-test-key'};let reply;x.w.GM_xmlhttpRequest=o=>{reply=o.onload;return {abort:()=>{}};};const pending=x.T.answer(q,x.T.currentEpoch());x.T.pause();reply({status:200,responseText:JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({choices:['A'],blanks:[],answer:'A',uncertain:false})}]}]})});await assert.rejects(pending);assert.equal(x.T.S.answers.size,0);assert.equal(q.root.querySelector('input').value,'');x.close();});
await test('provider switch loads SiliconFlow preset and preserves separate profiles',async()=>{const x=await setup();x.T.mount();const r=x.T.ui.root,p=r.querySelector('.provider');p.value='siliconflow';p.dispatchEvent(new x.w.Event('change'));assert.equal(r.querySelector('.base').value,'https://api.siliconflow.cn/v1');r.querySelector('.apikey').value='test-only-not-a-real-key';r.querySelector('.save').click();assert.equal(x.store.get('cirno.settings.v5').profiles.siliconflow.key,'test-only-not-a-real-key');p.value='openai';p.dispatchEvent(new x.w.Event('change'));assert.equal(r.querySelector('.apikey').value,'');assert.equal(r.querySelector('[data-setting="autoSubmit"]').checked,false);x.close();});
await test('title card without pageDiv advances after load grace',async()=>{const x=await setup();x.card.body.innerHTML='<h1>课程介绍</h1>';await x.T.tick();assert.deepEqual(x.counts().clicks,['cur102']);x.close();});
await test('missing frame and active chapter use next-section fallback',async()=>{const x=await setup({titleOnly:true});x.w.document.querySelector('#content1').remove();const b=x.w.document.createElement('button');b.id='prevNextFocusNext';let clicked=0;b.onclick=()=>clicked++;x.w.document.body.append(b);await x.T.tick();assert.equal(clicked,1);x.close();});
await test('newly loading empty card is not skipped early',async()=>{const x=await setup();x.card.body.innerHTML='<h1>课程介绍</h1>';x.T.S.changed=Date.now()-6000;await x.T.tick();assert.equal(x.counts().clicks.length,0);x.close();});
await test('active chapter takes priority over stale iframe URL',async()=>{const x=await setup();x.w.document.querySelector('.posCatalog_active').id='cur200';assert.equal(x.T.chapterId(),'200');x.close();});
await test('DeepSeek request disables thinking and enforces JSON',async()=>{const x=await setup();const p={...x.T.providers.deepseek,key:'fake'},r=x.T.makeRequest(p,{});assert.equal(r.body.thinking.type,'disabled');assert.equal(r.body.response_format.type,'json_object');assert.equal(r.body.max_tokens,8192);assert.equal(x.T.makeRequest({...p,thinking:true},{}).body.max_tokens,32768);x.close();});
await test('DeepSeek vision is selected per model, not provider',async()=>{const x=await setup();const p=x.T.providers.deepseek;assert.equal(x.T.supportsVision(p),true);assert.equal(x.T.supportsVision({...p,model:'deepseek-v4-pro'}),false);assert.equal(x.T.supportsVision({...p,model:'deepseek-reasoner'}),false);x.close();});
await test('reasoning-only response never masquerades as final answer',async()=>{const x=await setup();assert.throws(()=>x.T.decode({kind:'chat'},{choices:[{finish_reason:'stop',message:{content:null,reasoning_content:'thinking'}}]}),/最终答案/);x.close();});
await test('JSON surrounded by text and compact choices are normalized',async()=>{const x=await setup();const a=x.T.decode({kind:'chat'},{choices:[{finish_reason:'stop',message:{content:'答案如下：\n{"choices":"a,c","explanation":"依据"}\n以上。'}}]});assert.equal(a.choices.join(','),'A,C');assert.equal(a.uncertain,false);x.close();});
await test('manual model change persists and select matches it',async()=>{const x=await setup();x.T.mount();const r=x.T.ui.root,p=r.querySelector('.provider');p.value='deepseek';p.dispatchEvent(new x.w.Event('change'));const m=r.querySelector('.model');m.value='deepseek-v4-pro';m.dispatchEvent(new x.w.Event('change'));assert.equal(x.T.profile().model,'deepseek-v4-pro');assert.equal(r.querySelector('.modelSelect').value,'deepseek-v4-pro');assert(r.querySelector('.visionHint').textContent.includes('deepseek-flash'));x.close();});
await test('switching panels keeps toolbar position stable',async()=>{const x=await setup();x.T.mount();x.T.ui.ball.click();const top=x.T.ui.panel.style.top;x.T.ui.showTab('ai');assert.equal(x.T.ui.panel.style.top,top);x.T.ui.showTab('answers');assert.equal(x.T.ui.panel.style.top,top);x.w.document.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(x.T.ui.panel.hidden,true);x.close();});
function mockAnswers(x,answers){let calls=0,requests=[];x.T.cfg.provider='deepseek';x.T.cfg.profiles.deepseek={key:'fake-test-key'};x.w.GM_xmlhttpRequest=o=>{requests.push(o);const a=answers[Math.min(calls++,answers.length-1)];setTimeout(()=>o.onload({status:200,responseText:JSON.stringify({model:'deepseek-flash',choices:[{finish_reason:'stop',message:{content:JSON.stringify(a)}}]})}),0);return {abort:()=>{}};};return {count:()=>calls,requests};}
const certain={choices:['B'],blanks:[],answer:'B',uncertain:false},uncertain={choices:[],blanks:[],answer:'',uncertain:true,reason_code:'missing_context',uncertainty_reason:'缺少题目引用的阅读材料'};
await test('thinking strength is passed exactly and timeout is bounded',async()=>{const x=await setup();for(const effort of ['low','high','max']){const req=x.T.makeRequest({...x.T.providers.deepseek,thinking:true,effort},{});assert.equal(req.body.reasoning_effort,effort);assert.equal(req.body.thinking.type,'enabled');}assert.equal(x.T.responseTimeout({timeoutSeconds:600}),600000);assert.equal(x.T.responseTimeout({timeoutSeconds:1}),30000);assert.equal(x.T.responseTimeout({timeoutSeconds:99999}),900000);x.close();});
await test('uncertain answer reports reason and retries only configured count',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card)),m=mockAnswers(x,[uncertain]);x.T.cfg.uncertainRetries=1;await assert.rejects(x.T.answer(q,x.T.currentEpoch()),e=>e.code==='UNCERTAIN'&&e.message.includes('阅读材料'));assert.equal(m.count(),2);assert.equal(x.T.S.answers.size,0);assert(x.T.S.report.some(s=>s.includes('缺少材料')));assert.equal(q.root.querySelector('input').value,'');x.close();});
await test('uncertain answer can succeed on review and uses selected timeout',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card)),m=mockAnswers(x,[uncertain,certain]);x.T.cfg.profiles.deepseek.timeoutSeconds=600;const a=await x.T.answer(q,x.T.currentEpoch());assert.equal(a.choices[0],'B');assert.equal(m.count(),2);assert.equal(m.requests[0].timeout,600000);assert(JSON.parse(m.requests[1].data).messages[1].content.includes('previous_uncertainty'));x.close();});
await test('zero uncertainty retries sends exactly one request',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card)),m=mockAnswers(x,[uncertain]);x.T.cfg.uncertainRetries=0;await assert.rejects(x.T.answer(q,x.T.currentEpoch()));assert.equal(m.count(),1);x.close();});
await test('API errors do not start uncertainty retry loop',async()=>{const x=await setup();const q=x.T.parseQuestion(question(x.card));x.T.cfg.profiles.openai={key:'fake'};let calls=0;x.w.GM_xmlhttpRequest=o=>{calls++;setTimeout(()=>o.onload({status:401,responseText:'{}'}),0);return {abort:()=>{}};};await assert.rejects(x.T.answer(q,x.T.currentEpoch()),/401/);assert.equal(calls,1);x.close();});
await test('full auto enables video, homework and submission together',async()=>{const x=await setup();x.T.setFullAuto(true);assert.equal(x.T.cfg.video,true);assert.equal(x.T.cfg.homework,true);assert.equal(x.T.cfg.autoSubmit,true);assert.equal(x.T.cfg.popup,'ai');assert.equal(x.T.cfg.popupSubmit,true);x.close();});
await test('full auto started on quiz checks video first',async()=>{const x=await setup({video:true});x.w.document.querySelector('#dct1').classList.remove('active');x.w.document.querySelector('#dct2').classList.add('active');x.T.S.key=x.T.pageKey();x.T.setFullAuto(true);await x.T.tick();assert.deepEqual(x.counts().clicks,['dct1']);assert.equal(x.counts().plays,0);x.close();});
await test('full auto skips completed video and moves to quiz',async()=>{const x=await setup({video:true,complete:true});x.T.setFullAuto(true);await x.T.tick();assert.equal(x.counts().plays,0);assert.deepEqual(x.counts().clicks,['dct2']);x.close();});
await test('full auto returns to earlier quiz tab after later video tab',async()=>{const x=await setup();const a=x.w.document.querySelector('#dct1'),b=x.w.document.querySelector('#dct2');a.title='章节测验';a.classList.remove('active');b.title='视频';b.classList.add('active');x.T.S.key=x.T.pageKey();x.T.setFullAuto(true);x.T.advance();assert.deepEqual(x.counts().clicks,['dct1']);x.close();});
await test('full auto does not revisit processed video after quiz',async()=>{const x=await setup({video:true});const a=x.w.document.querySelector('#dct1'),b=x.w.document.querySelector('#dct2');x.T.setFullAuto(true);x.T.S.cardDone.add(x.T.cardIdentity(a));a.classList.remove('active');b.classList.add('active');x.T.S.key=x.T.pageKey();x.T.advance();assert.deepEqual(x.counts().clicks,['cur102']);x.close();});
await test('video wins over homework wrapper earlier in the same card',async()=>{const x=await setup({video:true});const w=x.card.createElement('div');w.className='ans-attach-ct';w.innerHTML='<span class="ans-job-icon" aria-label="任务点未完成"></span><iframe src="/ananas/modules/work/index.html"></iframe>';x.card.querySelector('#pageDiv').prepend(w);x.T.setFullAuto(true);await x.T.tick();assert.equal(x.counts().plays,1);assert.equal(x.counts().clicks.length,0);x.close();});
await test('full auto retains uncertain question, fills next one, never submits incomplete page',async()=>{const x=await setup({quiz:true});const r1=question(x.card),r2=question(x.card);r2.querySelectorAll('[qid]').forEach(e=>e.setAttribute('qid','200'));r2.querySelector('input').id='answer200';let submits=0,saves=0;for(const [cls,label,fn]of [['btnSubmit','提交',()=>submits++],['btnSave','暂时保存',()=>saves++]]){const b=x.card.createElement('button');b.className=cls;b.textContent=label;b.onclick=fn;x.card.body.append(b);}mockAnswers(x,[uncertain,certain]);x.T.setFullAuto(true);x.T.cfg.uncertainRetries=0;await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(r1.querySelector('input').value,'');assert.equal(r2.querySelector('input').value,'B');assert.equal(submits,0);assert.equal(saves,1);assert.equal(x.T.S.deferred.size,1);assert.equal(x.store.get('cirno.pending.v5').length,1);assert.equal(x.T.S.started,true);assert.equal(x.counts().clicks.length,1);x.close();});
await test('resolved question is removed from pending list',async()=>{const x=await setup({quiz:true});const r=question(x.card,{filled:true}),q=x.T.parseQuestion(r);x.T.deferQuestion(q,'旧的不确定原因');x.T.cfg.homework=true;await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(x.T.S.deferred.size,0);assert.equal(x.store.get('cirno.pending.v5').length,0);x.close();});
await test('thinking controls save effort and wait limit',async()=>{const x=await setup();x.T.mount();const r=x.T.ui.root,p=r.querySelector('.provider');p.value='deepseek';p.dispatchEvent(new x.w.Event('change'));r.querySelector('.thinking').checked=true;r.querySelector('.thinking').dispatchEvent(new x.w.Event('change'));r.querySelector('.effort').value='max';r.querySelector('.effort').dispatchEvent(new x.w.Event('change'));r.querySelector('.timeout').value='600';r.querySelector('.timeout').dispatchEvent(new x.w.Event('change'));assert.equal(x.T.profile().thinking,true);assert.equal(x.T.profile().effort,'max');assert.equal(x.T.profile().timeoutSeconds,600);x.close();});
await test('turning off auto submission exits full-auto mode',async()=>{const x=await setup();x.T.mount();x.T.setFullAuto(true);const e=x.T.ui.root.querySelector('[data-setting="autoSubmit"]');e.checked=false;e.dispatchEvent(new x.w.Event('change'));assert.equal(x.T.cfg.fullAuto,false);assert.equal(x.T.cfg.autoSubmit,false);x.close();});
function recoveryHarness(x){
  const a=x.w.document.createElement('a');a.id='contentFocus';a.href='https://mooc2-ans.chaoxing.com/mooc2-ans/mycourse/stu?courseid=course';a.textContent='返回课程';x.w.document.body.append(a);
  const moves=[];x.T.recoveryIO.go=url=>moves.push(url);x.T.recoveryIO.refresh=()=>moves.push('refresh');return moves;
}
await test('recovery remembers active AJAX chapter and navigates only once',async()=>{const x=await setup();const moves=recoveryHarness(x);x.w.document.querySelector('#cur100').id='cur109';x.T.recoverPage('网络异常');assert.equal(moves.length,1);assert.equal(x.T.readRecovery().stage,'course');assert.equal(new URL(x.T.readRecovery().studyUrl).searchParams.get('chapterId'),'109');assert.equal(x.T.S.started,false);await x.T.recoveryTick();assert.equal(moves.length,1);x.close();});
await test('course overview refreshes once, then returns to original chapter',async()=>{const x=await setup();recoveryHarness(x);x.T.recoverPage('网络异常');let record=x.T.readRecovery();x.close();const y=await setup({overview:true});const moves=recoveryHarness(y);y.store.set('cirno.recovery.v5.test-tab',record);await y.T.recoveryBoot();assert.deepEqual(moves,['refresh']);assert.equal(y.T.readRecovery().stage,'refreshed');record=y.T.readRecovery();y.close();const z=await setup({overview:true});const out=recoveryHarness(z);z.store.set('cirno.recovery.v5.test-tab',record);await z.T.recoveryBoot();assert.deepEqual(out,[record.studyUrl]);assert.equal(z.T.readRecovery().stage,'entering');z.close();});
await test('failed reentry waits ten minutes, then performs exactly one retry',async()=>{const x=await setup();const moves=recoveryHarness(x);x.T.recoverPage('网络异常');const r=x.T.readRecovery();x.store.set('cirno.recovery.v5.test-tab',{...r,stage:'monitoring'});x.T.S.started=true;x.T.S.recoveryLeaving=false;x.T.recoverPage('服务繁忙');assert.equal(x.T.readRecovery().stage,'waiting');assert.ok(x.T.readRecovery().retryAt-Date.now()>599000);await x.T.recoveryTick();assert.equal(moves.length,1);x.store.set('cirno.recovery.v5.test-tab',{...x.T.readRecovery(),retryAt:Date.now()-1});await x.T.recoveryTick();assert.equal(moves.length,2);assert.equal(x.T.readRecovery().attempts,2);await x.T.recoveryTick();assert.equal(moves.length,2);x.close();});
await test('retry limit stops recovery and manual pause cancels scheduled retry',async()=>{const x=await setup();const moves=recoveryHarness(x);x.T.recoverPage('网络异常');const r=x.T.readRecovery();x.store.set('cirno.recovery.v5.test-tab',{...r,attempts:3,stage:'monitoring'});x.T.S.started=true;x.T.recoverPage('服务繁忙');assert.equal(x.T.readRecovery(),null);assert.match(x.T.S.status,/连续恢复 3 次/);x.store.set('cirno.recovery.v5.test-tab',{...r,stage:'waiting',retryAt:0});x.T.pause();await x.T.recoveryTick();assert.equal(moves.length,1);assert.equal(x.T.readRecovery(),null);x.close();});
await test('normal confirmation and question text never trigger recovery',async()=>{const x=await setup();question(x.card).append('网络异常，如何处理？');const box=x.w.document.createElement('div');box.id='workpopFocus';box.textContent='确认提交？';x.w.document.body.append(box);assert.equal(x.T.pageError(),null);box.textContent='系统繁忙，请稍后再试';assert.equal(x.T.pageError().kind,'retry');box.hidden=true;assert.equal(x.T.pageError(),null);x.close();});
await test('captcha pauses without navigation and unconfirmed submission is not retried',async()=>{const x=await setup();const moves=recoveryHarness(x);const box=x.w.document.createElement('div');box.setAttribute('role','dialog');box.textContent='请完成安全验证';x.w.document.body.append(box);await x.T.recoveryTick();assert.equal(x.T.S.started,false);assert.equal(moves.length,0);box.remove();x.T.S.started=true;x.T.S.submit={at:Date.now()};x.T.recoverPage('网络异常');assert.equal(moves.length,0);assert.match(x.T.S.status,/提交结果尚未确认/);x.close();});
await test('recovery validates destinations and can use remembered return link',async()=>{const x=await setup();recoveryHarness(x);assert.equal(x.T.safeCourseURL('https://chaoxing.com.evil.test/mycourse/studentstudy'),null);assert.equal(x.T.safeCourseURL('javascript:alert(1)'),null);x.T.rememberReturn();x.w.document.querySelector('#contentFocus').remove();assert.ok(x.T.recoveryContext()?.courseUrl);x.close();});
await test('disabled recovery pauses and failed navigation enters cooldown',async()=>{const x=await setup();const moves=recoveryHarness(x);x.T.cfg.recover=false;x.T.recoverPage('网络异常');assert.equal(moves.length,0);x.T.cfg.recover=true;x.T.S.started=true;x.T.recoverPage('网络异常');const r=x.T.readRecovery();x.store.set('cirno.recovery.v5.test-tab',{...r,at:Date.now()-31000});await x.T.recoveryTick();assert.equal(x.T.readRecovery().stage,'waiting');assert.equal(moves.length,1);x.close();});
await test('successful reentry resumes and clears recovery after healthy window',async()=>{const x=await setup({video:true});recoveryHarness(x);x.T.recoverPage('网络异常');const r=x.T.readRecovery();x.store.set('cirno.recovery.v5.test-tab',{...r,stage:'entering'});x.T.S.recoveryLeaving=false;await x.T.recoveryBoot();assert.equal(x.T.readRecovery().stage,'monitoring');assert.equal(x.T.S.started,true);x.store.set('cirno.recovery.v5.test-tab',{...x.T.readRecovery(),healthySince:Date.now()-61000});x.T.S.lastVideoProgress=Date.now();await x.T.recoveryTick();assert.equal(x.T.readRecovery(),null);x.close();});
await test('recovery wait controls persist bounded values and cancel countdown',async()=>{const x=await setup();recoveryHarness(x);x.T.mount();const ui=x.T.ui.root;const minutes=ui.querySelector('[data-setting="recoveryMinutes"]');minutes.value='200';minutes.dispatchEvent(new x.w.Event('change'));assert.equal(x.T.cfg.recoveryMinutes,120);x.T.recoverPage('网络异常');const r=x.T.readRecovery();x.store.set('cirno.recovery.v5.test-tab',{...r,stage:'waiting',retryAt:Date.now()+60000});x.T.S.recoveryLeaving=false;await x.T.recoveryTick();assert.equal(x.T.ui.cancelRecovery.hidden,false);x.T.ui.cancelRecovery.click();assert.equal(x.T.readRecovery(),null);assert.equal(x.T.ui.cancelRecovery.hidden,true);x.close();});
await test('empty homework load times out into recovery instead of hanging',async()=>{const x=await setup({quiz:true});const moves=recoveryHarness(x);x.T.cfg.homework=true;x.T.S.changed=Date.now()-46000;await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(moves.length,1);assert.equal(x.T.readRecovery().stage,'course');x.close();});
await test('shuffled backend letters map to visible single-choice labels',async()=>{
  const x=await setup(),fixture=JSON.parse(fs.readFileSync(new URL('font-fixture.json',import.meta.url),'utf8'));x.card.body.innerHTML=fixture.question;
  const root=x.card.querySelector('.TiMu');for(const li of root.querySelectorAll('li'))li.onclick=()=>{for(const item of root.querySelectorAll('li')){item.setAttribute('aria-checked',String(item===li));item.querySelector('.num_option').classList.toggle('check_answer',item===li);}root.querySelector('input').value=li.querySelector('.num_option').getAttribute('data');};
  const q=x.T.parseQuestion(root);assert.deepEqual(Array.from(q.options,o=>[o.label,o.value]),[['A','D'],['B','C'],['C','B'],['D','A']]);await x.T.fill(q,{choices:['C']},x.T.currentEpoch());assert.equal(root.querySelector('input').value,'B');assert.equal(q.options[2].el.getAttribute('aria-checked'),'true');assert.equal(q.options[0].el.getAttribute('aria-checked'),'false');x.close();
});
await test('shuffled multi-choice values are separate from displayed letters',async()=>{
  const x=await setup(),r=question(x.card,{multi:true});const letters=['C','A','B'];[...r.querySelectorAll('.num_option')].forEach((e,i)=>e.setAttribute('data',letters[i]));const q=x.T.parseQuestion(r);await x.T.fill(q,{choices:['A','C']},x.T.currentEpoch());assert.equal(r.querySelector('input').value,'CB');assert.equal(x.T.checked(q,q.options[1]),false);for(const e of r.querySelectorAll('.check_answer'))e.classList.remove('check_answer');assert.equal(x.T.checked(q,q.options[0]),true);assert.equal(x.T.checked(q,q.options[2]),true);x.close();
});
await test('question ID is retained when only the outer wrapper has it',async()=>{const x=await setup(),r=question(x.card),outer=x.card.createElement('div');outer.id='question405732102';r.querySelectorAll('[qid]').forEach(e=>e.removeAttribute('qid'));r.replaceWith(outer);outer.append(r);assert.equal(x.T.parseQuestion(r).id,'405732102');x.close();});
await test('re-answer replaces existing choices but does not submit',async()=>{const x=await setup({quiz:true}),r=question(x.card,{filled:true});let submits=0;const b=x.card.createElement('button');b.className='btnSubmit';b.textContent='提交';b.onclick=()=>submits++;x.card.body.append(b);mockAnswers(x,[certain]);x.T.cfg.autoSubmit=true;x.T.S.single=true;x.T.S.replaceAnswers=true;await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(r.querySelector('input').value,'B');assert.equal(submits,0);assert.match(x.T.S.status,/重新填写/);x.close();});
await test('answers cached for one card are not reused on another card',async()=>{const x=await setup(),q=x.T.parseQuestion(question(x.card)),m=mockAnswers(x,[certain,{...certain,choices:['C'],answer:'C'}]);await x.T.answer(q,x.T.currentEpoch());x.w.document.querySelector('#dct1').setAttribute('cardid','another');const a=await x.T.answer(q,x.T.currentEpoch());assert.equal(a.choices[0],'C');assert.equal(m.count(),2);x.close();});
function judgeFixture(x,index=3){
  const samples=JSON.parse(fs.readFileSync(new URL('judge-fixture.json',import.meta.url),'utf8'));x.card.body.innerHTML=samples[index];const root=x.card.querySelector('.TiMu');
  for(const li of root.querySelectorAll('li'))li.onclick=()=>{const multi=li.getAttribute('qtype')==='1',cls=multi?'check_answer_dx':'check_answer',mark=li.querySelector('.num_option,.num_option_dx'),was=mark.classList.contains(cls);if(!multi)for(const item of root.querySelectorAll('li')){item.setAttribute('aria-checked','false');item.querySelector('span').classList.remove(cls);}mark.classList.toggle(cls,!was);li.setAttribute('aria-checked',String(!was));root.querySelector('input').value=[...root.querySelectorAll('.'+cls)].map(e=>e.getAttribute('data')).join('');};
  return root;
}
await test('standard true false controls can select either answer and replace it',async()=>{const x=await setup(),r=judgeFixture(x),q=x.T.parseQuestion(r);assert.equal(q.judge,true);for(const [choice,value]of [['A','true'],['B','false'],['A','true']]){await x.T.fill(q,{choices:[choice]},x.T.currentEpoch());assert.equal(r.querySelector('input').value,value);}x.close();});
await test('judgement synonyms map to visible labels, including false',async()=>{const x=await setup(),r=judgeFixture(x),q=x.T.parseQuestion(r);for(const raw of ['TRUE','FALSE','对','错','√','×']){const a={choices:[raw]};await x.T.fill(q,a,x.T.currentEpoch());assert.equal(r.querySelector('input').value,['TRUE','对','√'].includes(raw)?'true':'false');}const a=x.T.decode({kind:'chat'},{choices:[{message:{content:JSON.stringify({choices:false,answer:false})}}]});await x.T.fill(q,a,x.T.currentEpoch());assert.equal(r.querySelector('input').value,'false');x.close();});
await test('standard multi-choice dx markers preserve backend shuffle',async()=>{const x=await setup(),r=judgeFixture(x,2),q=x.T.parseQuestion(r);assert.equal(q.options[0].value,'C');await x.T.fill(q,{choices:['A','D']},x.T.currentEpoch());assert.equal(r.querySelector('input').value,'CD');await x.T.fill(q,{choices:['B','C']},x.T.currentEpoch());assert.equal(r.querySelector('input').value,'BA');x.close();});
await test('authoritative saved false overrides stale ARIA state',async()=>{const x=await setup(),r=judgeFixture(x),q=x.T.parseQuestion(r);r.querySelector('input').value='false';q.options[0].el.setAttribute('aria-checked','true');assert.equal(x.T.checked(q,q.options[0]),false);assert.equal(x.T.checked(q,q.options[1]),true);x.close();});
await test('video error waits five minutes then returns to course exactly once',async()=>{const x=await setup({video:true}),moves=recoveryHarness(x),v=x.card.querySelector('iframe').contentDocument.querySelector('video');Object.defineProperty(v,'error',{value:{code:4}});await x.T.playVideo(v);assert.equal(x.T.S.started,true);assert.equal(moves.length,0);x.T.S.videoWatch.at=Date.now()-299000;await x.T.playVideo(v);assert.equal(moves.length,0);x.T.S.videoWatch.at=Date.now()-300001;await x.T.playVideo(v);assert.equal(moves.length,1);assert.equal(x.T.S.started,false);x.close();});
await test('playback progress resets watchdog and manual pause is respected',async()=>{const x=await setup({video:true}),moves=recoveryHarness(x),v=x.card.querySelector('iframe').contentDocument.querySelector('video');await x.T.playVideo(v);x.T.S.videoWatch.at=Date.now()-300001;v.currentTime=2;await x.T.playVideo(v);assert.equal(moves.length,0);assert.ok(Date.now()-x.T.S.videoWatch.at<1000);x.T.S.videoWatch.at=Date.now()-300001;x.T.S.manual.add(v);await x.T.playVideo(v);assert.equal(moves.length,0);assert.equal(x.T.S.videoWatch,null);x.close();});
await test('missing video and stalled progress also recover after five minutes',async()=>{const x=await setup({video:true}),moves=recoveryHarness(x);x.T.videoWatchdog(null);x.T.S.videoWatch.at=Date.now()-300001;x.T.videoWatchdog(null);assert.equal(moves.length,1);x.close();});
await test('stalled reentry does not clear the bounded recovery attempt count',async()=>{const x=await setup({video:true});recoveryHarness(x);x.T.recoverPage('视频加载失败');const r=x.T.readRecovery();x.store.set('cirno.recovery.v5.test-tab',{...r,stage:'monitoring',healthySince:Date.now()-61000});x.T.S.recoveryLeaving=false;x.T.S.started=true;x.store.set('cirno.lock.v5',{owner:'test-tab',at:Date.now()});x.T.videoWatchdog(null);await x.T.recoveryTick();assert.equal(x.T.readRecovery().attempts,1);x.close();});
await test('all four shuffled multi-choice options are visibly selected, not falsely accepted',async()=>{const x=await setup(),r=judgeFixture(x,2),q=x.T.parseQuestion(r);await x.T.fill(q,{choices:['A','B','C','D']},x.T.currentEpoch());assert.equal(r.querySelectorAll('.check_answer_dx').length,4);assert.equal(r.querySelector('input').value,'CBAD');x.close();});
function networkFixture(x,failures){
  x.T.cfg.provider='deepseek';x.T.cfg.profiles.deepseek={key:'fake-test-key'};let calls=0;
  const native=x.w.setTimeout.bind(x.w);x.w.setTimeout=(fn,ms,...args)=>native(fn,ms===1000?1:ms,...args);
  x.w.GM_xmlhttpRequest=o=>{const index=calls++;setTimeout(()=>{const f=failures[index];if(f==='network')o.onerror();else if(f==='timeout')o.ontimeout();else if(f)o.onload({status:f,responseText:'{}'});else o.onload({status:200,responseText:JSON.stringify({choices:[{message:{content:JSON.stringify({choices:['B'],answer:'B'})}}]})});},0);return {abort:()=>o.onabort()};};return ()=>calls;
}
await test('transient network error retries same question without duplicate filling',async()=>{const x=await setup(),r=question(x.card),q=x.T.parseQuestion(r),calls=networkFixture(x,['network']);await x.T.fill(q,await x.T.answer(q,x.T.currentEpoch()),x.T.currentEpoch());assert.equal(calls(),2);assert.equal(x.T.S.calls,2);assert.equal(r.querySelector('input').value,'B');x.close();});
await test('API transient retries stop after three attempts',async()=>{const x=await setup(),q=x.T.parseQuestion(question(x.card)),calls=networkFixture(x,[503,'timeout','network']);await assert.rejects(x.T.answer(q,x.T.currentEpoch()),/API 网络连接失败/);assert.equal(calls(),3);assert.equal(x.T.S.answers.size,0);x.close();});
await test('credentials and quota errors are not retried',async()=>{for(const code of [401,403,404,429]){const x=await setup(),q=x.T.parseQuestion(question(x.card)),calls=networkFixture(x,[code]);await assert.rejects(x.T.answer(q,x.T.currentEpoch()),new RegExp(String(code)));assert.equal(calls(),1);x.close();}});
await test('pausing during backoff prevents another paid request',async()=>{const x=await setup(),q=x.T.parseQuestion(question(x.card)),calls=networkFixture(x,['network']);const native=x.w.setTimeout.bind(x.w);x.w.setTimeout=(fn,ms,...args)=>{if(ms===1000)x.T.pause();return native(fn,ms,...args);};await assert.rejects(x.T.answer(q,x.T.currentEpoch()),/取消/);assert.equal(calls(),1);x.close();});
await test('already available fonts are not force-loaded again',async()=>{const x=await setup(),r=question(x.card);r.style.fontFamily='Known';let loads=0;Object.defineProperty(x.card,'fonts',{value:{check:()=>true,load:()=>{loads++;throw Error('unexpected');}}});await x.T.loadQuestionFonts({root:r});assert.equal(loads,0);x.close();});
await test('font network failure is identified before any API request',async()=>{const x=await setup(),r=question(x.card,{encrypted:true});r.querySelector('.font-cxsecret').style.fontFamily='BrokenSecret';x.w.html2canvas=()=>{throw Error('must not render');};Object.defineProperty(x.card,'fonts',{value:{check:()=>false,load:()=>Promise.reject(new x.w.DOMException('A network error occurred.','NetworkError'))}});const calls=networkFixture(x,[]);await assert.rejects(x.T.answer(x.T.parseQuestion(r),x.T.currentEpoch()),/题目字体加载失败.*尚未发送/);assert.equal(calls(),0);assert.equal(x.T.S.calls,0);assert(x.T.S.report.some(s=>s.includes('截图阶段')));x.close();});
await test('resource load timeout identifies failure stage',async()=>{const x=await setup();await assert.rejects(x.T.captureStage('题目字体加载',()=>new Promise(()=>{}),5),/题目字体加载失败/);x.close();});
await test('network retry exhaustion preserves previously filled answers without submission',async()=>{const x=await setup({quiz:true});const first=question(x.card,{filled:true}),second=question(x.card);second.querySelector('input').id='answer101';second.querySelectorAll('[qid]').forEach(e=>e.setAttribute('qid','101'));x.T.cfg.homework=true;x.T.cfg.autoSubmit=true;const calls=networkFixture(x,['network','network','network']);await x.T.doHomework(x.card,x.T.currentEpoch());assert.equal(first.querySelector('input').value,'A');assert.equal(second.querySelector('input').value,'');assert.equal(x.T.S.started,false);assert.equal(calls(),3);assert.equal(x.T.S.submit,null);x.close();});
await test('unrelated broken body font cannot block encrypted question capture',async()=>{const x=await setup(),r=question(x.card,{encrypted:true});r.style.fontFamily='BrokenWebFont';r.querySelector('.font-cxsecret').style.fontFamily='font-cxsecret';const requested=[];Object.defineProperty(x.card,'fonts',{value:{check:()=>false,load:font=>{requested.push(font);return font.includes('Broken')?Promise.reject(Error('network')):Promise.resolve([]);}}});await x.T.loadQuestionFonts({root:r});assert.deepEqual(requested,['18px font-cxsecret']);x.close();});
await test('multi type remains correct when title is encrypted and accessibility role is absent',async()=>{for(const signal of ['qtype','marker','handler']){const x=await setup(),r=question(x.card);r.querySelector('.Zy_TItle').textContent='乱码题干';for(const li of r.querySelectorAll('li')){li.removeAttribute('role');if(signal==='qtype')li.setAttribute('qtype','1');if(signal==='marker')li.querySelector('span').className='num_option_dx';if(signal==='handler')li.setAttribute('onclick','addMultipleChoice(this);');}assert.equal(x.T.parseQuestion(r).type,'multi',signal);x.close();}});
await test('multi request explicitly allows all correct choices',async()=>{const x=await setup(),req=x.T.makeRequest({...x.T.providers.deepseek,key:'fake',thinking:true,effort:'high'},{type:'multi',question:'test',options:['A','B','C','D']});const data=JSON.parse(req.body.messages[1].content);assert.equal(data.question_type,'多选题');assert(data.answer_checks.includes('可以全选'));assert.equal(data.output_example.choices.join(''),'AC');assert.equal(req.body.thinking.type,'enabled');assert.equal(req.body.reasoning_effort,'high');x.close();});
await test('single returned choice on a multi question is reviewed then all answers filled',async()=>{const x=await setup(),q=x.T.parseQuestion(question(x.card,{multi:true})),m=mockAnswers(x,[{...certain,choices:['B']},{...certain,choices:['A','B','C']}]);const a=await x.T.answer(q,x.T.currentEpoch());await x.T.fill(q,a,x.T.currentEpoch());assert.equal(m.count(),2);assert.equal(q.root.querySelector('input').value,'ABC');assert(JSON.parse(m.requests[1].data).messages[1].content.includes('本题明确是多选题'));x.close();});
await test('single-choice review is bounded and never pads a multi answer',async()=>{const x=await setup(),q=x.T.parseQuestion(question(x.card,{multi:true})),m=mockAnswers(x,[certain]);const a=await x.T.answer(q,x.T.currentEpoch());assert.equal(m.count(),2);assert.equal(a.choices.join(''),'B');x.close();});
const flowStore='cirno.flow.v5.test-tab';
await test('API call 101 remains available',async()=>{const x=await setup(),q=x.T.parseQuestion(question(x.card)),m=mockAnswers(x,[certain]);x.T.S.calls=100;const a=await x.T.answer(q,x.T.currentEpoch());assert.equal(a.choices[0],'B');assert.equal(x.T.S.calls,101);assert.equal(m.count(),1);x.close();});
await test('full-auto error preserves running state and manual completion advances',async()=>{const x=await setup({quiz:true});x.T.setFullAuto(true);x.T.fault('AI 输出未完成');assert(x.T.S.started);x.card.body.innerHTML='<div class="newAnswerBx">已完成</div>';assert(await x.T.continuityTick());assert.equal(x.T.S.autoHold,null);assert.equal(x.counts().clicks.length,1);x.close();});
await test('manually filled pending question releases hold without calling AI',async()=>{const x=await setup({quiz:true});x.T.setFullAuto(true);const r=question(x.card);x.T.fault('AI 输出未完成');r.querySelector('li').click();assert.equal(await x.T.continuityTick(),false);assert.equal(x.T.S.autoHold,null);assert.equal(x.T.S.calls,0);x.close();});
await test('full-auto error waits sixty seconds before first refresh',async()=>{const x=await setup();x.T.setFullAuto(true);const moves=recoveryHarness(x);x.T.fault('AI 输出未完成');await x.T.continuityTick();assert.equal(moves.length,0);x.T.S.autoHold.at-=61000;await x.T.continuityTick();assert.equal(moves.length,1);assert.equal(x.T.readFlow().phase,'refresh');assert.equal(new URL(moves[0]).searchParams.get('chapterId'),'100');await x.T.continuityTick();assert.equal(moves.length,1);x.close();});
await test('refresh resume then repeated failure returns through course and skips section',async()=>{
  const x=await setup();x.T.setFullAuto(true);const moves=recoveryHarness(x);x.T.recoverContinuous('卡住');let record=x.T.readFlow();assert.equal(record.phase,'refresh');x.close();
  const y=await setup();y.T.setFullAuto(true);const retry=recoveryHarness(y);y.store.set(flowStore,record);await y.T.flowBoot();assert.equal(y.T.readFlow().phase,'monitor');assert(y.T.S.started);y.T.recoverContinuous('仍卡住');record=y.T.readFlow();assert.equal(record.phase,'return');assert.deepEqual([...record.skipped],['100']);assert.equal(y.T.S.deferred.size,1);assert.equal(retry[0],record.courseUrl);y.close();
  const z=await setup({overview:true});z.T.setFullAuto(true);const overviewMoves=recoveryHarness(z);z.store.set(flowStore,record);await z.T.flowBoot();assert.equal(overviewMoves[0],record.nextUrl);assert.equal(z.T.readFlow().phase,'next');record=z.T.readFlow();z.close();
  const n=await setup();n.T.setFullAuto(true);n.w.document.querySelector('#cur100').classList.remove('posCatalog_active');n.w.document.querySelector('#cur102').classList.add('posCatalog_active');n.store.set(flowStore,record);await n.T.flowBoot();assert(n.T.S.started);assert.equal(n.T.readFlow().phase,'fresh');assert(n.T.S.autoHold==null);assert.deepEqual([...n.T.readFlow().skipped],['100']);n.close();
});
await test('refresh without return link uses actual AJAX chapter',async()=>{const x=await setup();x.T.setFullAuto(true);const moves=[];x.T.recoveryIO.go=u=>moves.push(u);x.w.document.querySelector('#cur100').id='cur109';x.T.recoverContinuous('卡住');assert.equal(new URL(moves[0]).searchParams.get('chapterId'),'109');x.close();});
await test('pending submission refresh waits for result and does not resubmit',async()=>{const x=await setup({quiz:true});x.T.setFullAuto(true);recoveryHarness(x);question(x.card,{filled:true});let submits=0;const b=x.card.createElement('button');b.className='btnSubmit';b.textContent='提交';b.onclick=()=>submits++;x.card.body.append(b);x.T.S.submit={d:x.card,key:x.T.pageKey(),at:Date.now()};x.T.recoverContinuous('提交未响应');const r=x.T.readFlow();x.store.set(flowStore,r);await x.T.flowBoot();assert(x.T.S.autoHold.submission);await x.T.recoveryTick();assert.equal(submits,0);x.card.body.innerHTML='<div class="newAnswerBx">已提交</div>';await x.T.recoveryTick();assert.equal(x.T.S.submit,null);assert.equal(x.counts().clicks.length,1);x.close();});
await test('manual pause cancels automatic fallback and does not restart',async()=>{const x=await setup();x.T.setFullAuto(true);const moves=recoveryHarness(x);x.T.fault('失败');x.T.S.autoHold.at-=61000;x.T.pause();await x.T.recoveryTick();assert.equal(x.T.S.started,false);assert.equal(x.T.readFlow(),null);assert.equal(moves.length,0);x.close();});
await test('five minute no-progress guardian runs even while task is busy',async()=>{const x=await setup({video:true});x.T.setFullAuto(true);const moves=recoveryHarness(x);x.T.S.busy=true;x.T.progress();x.T.S.progress.at-=301000;await x.T.recoveryTick();assert.equal(moves.length,1);assert.equal(x.T.readFlow().phase,'refresh');x.close();});
await test('active API deadline and real video movement prevent premature recovery',async()=>{const x=await setup({video:true});x.T.setFullAuto(true);const moves=recoveryHarness(x);x.T.progress();x.T.S.progress.at-=301000;x.T.S.apiUntil=Date.now()+10000;await x.T.continuityTick();assert.equal(moves.length,0);x.T.S.apiUntil=0;const v=x.card.querySelector('iframe').contentDocument.querySelector('video');x.T.videoWatchdog(v,'播放');v.currentTime=2;x.T.videoWatchdog(v,'播放');await x.T.continuityTick();assert.equal(moves.length,0);assert(Date.now()-x.T.S.progress.at<1000);x.close();});
await test('reader parent survives transfer of control and resumes on completion',async()=>{const x=await setup();x.T.setFullAuto(true);const t={id:'r',parent:'test-tab',reader:'reader-tab',state:'active',at:Date.now()};x.T.S.waitReader=t;x.store.set('cirno.reader.v5',t);x.store.set('cirno.lock.v5',{owner:'reader-tab',at:Date.now()});await x.T.recoveryTick();assert(x.T.S.started);assert.equal(x.store.get('cirno.reader.v5').state,'active');x.store.set('cirno.reader.v5',{...t,state:'done'});x.store.set('cirno.lock.v5',null);await x.T.recoveryTick();assert.equal(x.T.S.waitReader,null);assert.equal(x.counts().clicks.length,1);x.close();});
await test('stalled child reader marks itself skipped and parent continues',async()=>{const x=await setup({reader:true});x.w.scrollBy=()=>{};const t={id:'r',reader:'test-tab',parent:'parent',state:'active',at:Date.now()};x.T.S.reading=t;x.store.set('cirno.reader.v5',t);x.T.recoveryIO.go=()=>{};x.T.recoverContinuous('卡住');x.T.S.flowLeaving=false;x.store.set(flowStore,{...x.T.readFlow(),phase:'monitor'});x.T.recoverContinuous('仍卡住');assert.equal(x.store.get('cirno.reader.v5').state,'skipped');assert.equal(x.T.S.started,false);x.close();});
await test('reader scrolling uses configured speed and nested scrolling container',async()=>{const x=await setup({reader:true});const el=x.w.document.querySelector('#ztMainBoxFocus');el.style.overflowY='auto';Object.defineProperties(el,{clientHeight:{value:300},scrollHeight:{value:2000}});el.scrollTop=0;let args;el.scrollBy=a=>{args=a;el.scrollTop+=a.top;};x.T.cfg.readSpeed=120;x.T.S.readerSignature=x.T.readIdentity();x.T.S.readerLast=Date.now()-1500;await x.T.readTick();assert.equal(x.T.readerScroller(),el);assert.equal(args.behavior,'smooth');assert(args.top>=179&&args.top<=190);assert.equal(x.counts().clicks.length,0);x.close();});
await test('reader observes configured dwell even after reaching bottom',async()=>{const x=await setup({reader:true});const s=x.w.document.documentElement;Object.defineProperty(x.w.document,'scrollingElement',{value:s});Object.defineProperty(s,'scrollHeight',{value:500});x.T.cfg.readSeconds=120;x.T.S.readerSignature=x.T.readIdentity();x.T.S.readerSince=Date.now()-60000;x.T.S.readerBottom=Date.now()-2000;await x.T.readTick();assert.equal(x.counts().clicks.length,0);x.T.S.readerSince-=61000;await x.T.readTick();assert.deepEqual(x.counts().clicks,['next']);x.close();});
await test('reader recognizes ordinary next-page links but rejects external links',async()=>{const x=await setup({reader:true});const a=x.w.document.querySelector('a');a.className='';assert.equal(x.T.readerNext(),a);a.href='https://example.org/next';assert.equal(x.T.readerNext(),undefined);assert.equal(x.T.flowURL('https://chaoxing.com.evil.test/zt/a'),null);x.close();});
await test('reader dwell longer than five minutes is not a stall',async()=>{const x=await setup({reader:true});x.T.cfg.readSeconds=900;x.T.progress();x.T.S.progress.at-=400000;assert.equal(await x.T.continuityTick(),false);x.close();});
await test('new reading and fallback settings persist bounded values',async()=>{const x=await setup();x.T.mount();for(const [key,value,expected] of [['readSpeed',160,160],['readSeconds',1800,1800],['stallSeconds',10,60]]){const field=x.T.ui.root.querySelector(`[data-setting="${key}"]`);field.value=value;field.dispatchEvent(new x.w.Event('change'));assert.equal(x.T.cfg[key],expected);assert.equal(x.store.get('cirno.settings.v5')[key],expected);}x.close();});
await test('full-auto captcha still stops without navigation',async()=>{const x=await setup();x.T.setFullAuto(true);const moves=recoveryHarness(x),b=x.w.document.createElement('div');b.setAttribute('role','dialog');b.textContent='请完成安全验证';x.w.document.body.append(b);x.T.progress();x.T.S.progress.at-=301000;await x.T.recoveryTick();assert.equal(x.T.S.started,false);assert.equal(moves.length,0);x.close();});
await test('Baka panel stays in viewport and clear of its icon at all edges',async()=>{
  for(const [width,height] of [[1440,900],[1024,360],[390,844],[320,480]])for(const [px,py] of [[10,10],[width-80,10],[10,height-80],[width-80,height-80],[width/2,height/2]]){
    const x=await setup();Object.defineProperties(x.w,{innerWidth:{value:width,writable:true},innerHeight:{value:height,writable:true}});x.store.set('cirno.position.v5',{x:px,y:py});x.T.mount();x.T.ui.ball.click();
    const p=x.T.ui.panel.style,b=x.T.ui.ball.style,pr={x:parseFloat(p.left),y:parseFloat(p.top),w:parseFloat(p.width),h:parseFloat(p.height)},br={x:parseFloat(b.left),y:parseFloat(b.top),w:66,h:66};
    assert(pr.x>=0&&pr.y>=0&&pr.x+pr.w<=width&&pr.y+pr.h<=height,JSON.stringify({width,height,pr}));
    assert(pr.x+pr.w<=br.x||br.x+br.w<=pr.x||pr.y+pr.h<=br.y||br.y+br.h<=pr.y,JSON.stringify({pr,br}));x.close();
  }
});
function pointer(x,type,px,py){const e=new x.w.MouseEvent(type,{clientX:px,clientY:py,button:0,bubbles:true,composed:true});Object.defineProperty(e,'pointerId',{value:1});x.T.ui.ball.dispatchEvent(e);}
await test('dragging saves position and suppresses only the following mouse click',async()=>{const x=await setup();x.T.mount();pointer(x,'pointerdown',950,680);pointer(x,'pointermove',760,430);pointer(x,'pointerup',760,430);x.T.ui.ball.dispatchEvent(new x.w.MouseEvent('click',{detail:1}));assert(x.T.ui.panel.hidden);assert(!x.T.ui.ball.classList.contains('dragging'));assert(x.store.has('cirno.position.v5'));x.T.ui.ball.click();assert(!x.T.ui.panel.hidden);x.close();});
await test('cancelled drag clears movement state and preserves keyboard toggle',async()=>{const x=await setup();x.T.mount();pointer(x,'pointerdown',950,680);pointer(x,'pointermove',800,500);pointer(x,'pointercancel',800,500);assert(!x.T.ui.ball.classList.contains('dragging'));assert(!x.T.ui.panel.classList.contains('dragging'));x.T.ui.ball.click();assert(!x.T.ui.panel.hidden);x.close();});
await test('rapid open-close-open cannot be hidden by a stale animation',async()=>{const x=await setup();x.T.mount();const animations=[];x.T.ui.panel.animate=()=>{const a={cancel(){this.cancelled=true;},onfinish:null};animations.push(a);return a;};x.T.ui.ball.click();assert(!x.T.ui.panel.hidden);x.T.ui.ball.click();assert(x.T.ui.panel.inert);const stale=animations[1].onfinish;x.T.ui.ball.click();stale();assert(!x.T.ui.panel.hidden);assert.equal(x.T.ui.panel.inert,false);assert.equal(x.T.ui.ball.getAttribute('aria-expanded'),'true');animations[2].onfinish();x.T.ui.ball.click();animations[3].onfinish();assert(x.T.ui.panel.hidden);x.close();});
await test('reduced motion skips animation and closes immediately',async()=>{const x=await setup();x.w.matchMedia=()=>({matches:true});x.T.mount();x.T.ui.panel.animate=()=>{throw Error('motion should be disabled');};x.T.ui.ball.click();assert(!x.T.ui.panel.hidden);x.T.ui.ball.click();assert(x.T.ui.panel.hidden);x.close();});
await test('branding and embedded artwork need no image network request',async()=>{const x=await setup();x.T.mount();assert.match(source,/@name\s+Baka助手/);assert.match(source,/@version\s+0\.9\s/);assert.equal(x.T.ui.root.querySelector('.title').textContent,'Baka助手');assert.equal(x.T.ui.root.querySelector('.tag').textContent,'0.9');assert(x.T.ui.ball.querySelector('image').getAttribute('href').startsWith('data:image/webp;base64,'));x.close();});
const authAccounts='baka.login.accounts.v1',authRequest='baka.login.resume.v1',lockKey='cirno.lock.v5';
function sharedStore(x,store){x.w.GM_getValue=(k,d)=>store.has(k)?store.get(k):d;x.w.GM_setValue=(k,v)=>store.set(k,v);}
function savedLogin(x,enabled=true){x.store.set(authAccounts,{'https://v8.chaoxing.com':{account:'dummy-user',password:'dummy-password',enabled}});let clicks=0;x.w.document.querySelector('#login').onclick=()=>clicks++;return ()=>clicks;}
await test('leaving page releases lease and preserves actual chapter checkpoint',async()=>{const x=await setup();await x.T.start(false,false,true);x.w.document.querySelector('#cur100').id='cur109';x.T.leavePage();assert.equal(x.store.get(lockKey),null);const c=x.store.get('baka.session.test-tab');assert.equal(c.chapter,'109');assert.equal(new URL(c.url).searchParams.get('chapterId'),'109');assert.equal(x.T.S.started,false);x.close();});
await test('old document cannot renew or release new instance lease',async()=>{const x=await setup(),y=await setup();sharedStore(y,x.store);assert(await x.T.acquire());assert(await y.T.acquire());const lease=x.store.get(lockKey);x.T.renewLease();x.T.release();assert.equal(x.store.get(lockKey),lease);assert.equal(x.T.ownsLease(),false);x.close();y.close();});
await test('simultaneous pages leave only one lease owner',async()=>{const x=await setup(),y=await setup({ownerId:'second'});sharedStore(y,x.store);x.store.set(lockKey,null);const results=await Promise.all([x.T.acquire(),y.T.acquire()]);assert.equal(results.filter(Boolean).length,1);assert.notEqual(x.T.ownsLease(),y.T.ownsLease());x.close();y.close();});
await test('fresh other page blocks until explicit takeover',async()=>{const x=await setup();x.T.mount();x.store.set(lockKey,{owner:'other',at:Date.now()});assert.equal(await x.T.acquire(),false);assert.equal(x.T.ui.takeover.hidden,false);assert(await x.T.acquire(true));assert(x.T.ownsLease());assert(x.T.ui.takeover.hidden);x.close();});
await test('waiting page resumes when former owner releases',async()=>{const x=await setup();x.store.set(lockKey,{owner:'other',at:Date.now()});await x.T.start(false,false,true);assert(x.T.S.lockWait);assert.equal(x.T.S.started,false);x.store.set(lockKey,null);await x.T.recoveryTick();assert(x.T.S.started);assert.equal(x.T.S.lockWait,null);x.close();});
await test('stale lease expires and back-forward restore respects manual pause',async()=>{const x=await setup();x.store.set(lockKey,{owner:'old',at:Date.now()-91000});await x.T.start(false,false,true);assert(x.T.S.started);x.T.leavePage();await x.T.restorePage({persisted:true});assert(x.T.S.started);x.T.pause();await x.T.restorePage({persisted:true});assert.equal(x.T.S.started,false);x.close();});
await test('saving login is explicit scoped disabled by default and removable',async()=>{const x=await setup({login:true});x.T.mountLogin();const f=x.T.loginForm();f.account.value='dummy-user';f.password.value='dummy-password';assert(x.T.saveLoginAccount());assert.equal(x.store.get(authAccounts)['https://v8.chaoxing.com'].enabled,false);assert(!x.T.redact('dummy-user dummy-password').includes('dummy'));x.T.clearLoginAccount();assert.equal(Object.keys(x.store.get(authAccounts)).length,0);x.close();});
await test('login refuses cross-origin form action',async()=>{const x=await setup({login:true});const calls=savedLogin(x);x.w.document.querySelector('form').action='https://example.org/login';assert.equal(x.T.loginForm(),null);await x.T.loginTick(true);assert.equal(calls(),0);x.close();});
await test('automatic login clicks only once and preserves attempt across reload',async()=>{const x=await setup({login:true}),calls=savedLogin(x);await x.T.loginTick();await x.T.loginTick();assert.equal(calls(),1);assert.equal(x.T.loginForm().account.value,'dummy-user');const y=await setup({login:true});sharedStore(y,x.store);let repeated=0;y.w.document.querySelector('#login').onclick=()=>repeated++;await y.T.loginTick();assert.equal(repeated,0);x.close();y.close();});
await test('visible verification prevents filling or clicking',async()=>{const x=await setup({login:true}),calls=savedLogin(x);x.w.document.querySelector('#captcha').hidden=false;await x.T.loginTick();assert.equal(calls(),0);assert.equal(x.T.loginForm().password.value,'');x.w.document.querySelector('#captcha').hidden=true;await x.T.loginTick();assert.equal(calls(),1);x.close();});
await test('manual account or password edits are not overwritten',async()=>{for(const field of ['account','password']){const x=await setup({login:true}),calls=savedLogin(x);x.T.loginForm()[field].value='manual-edit';await x.T.loginTick();assert.equal(calls(),0);assert.equal(x.T.loginForm()[field].value,'manual-edit');x.close();}});
await test('login errors and unaccepted terms prevent retry',async()=>{for(const html of ['<p role="alert">密码错误</p>','<label><input type="checkbox" required>协议</label>']){const x=await setup({login:true}),calls=savedLogin(x);x.w.document.querySelector('form').insertAdjacentHTML('beforeend',html);await x.T.loginTick();assert.equal(calls(),0);x.close();}});
await test('disabled credentials never auto-login and manual retry is bounded',async()=>{const x=await setup({login:true}),calls=savedLogin(x,false);await x.T.loginTick();assert.equal(calls(),0);await x.T.loginTick(true);await x.T.loginTick(true);assert.equal(calls(),1);x.close();});
await test('saved credentials on another origin never fill current form',async()=>{const x=await setup({login:true});x.store.set(authAccounts,{'https://passport2.chaoxing.com':{account:'dummy-user',password:'dummy-password',enabled:true}});await x.T.loginTick();assert.equal(x.T.loginForm().password.value,'');x.close();});
await test('manual pause cancels own auth checkpoint but preserves other page request',async()=>{const x=await setup();x.T.rememberSession(true);x.T.makeAuthRequest();assert(x.T.readAuth());x.T.pause();assert.equal(x.T.readAuth(),null);assert.equal(x.store.get('baka.session.test-tab'),null);x.store.set(authRequest,{owner:'other',url:x.w.location.href,at:Date.now()});x.T.cancelAuthResume();assert(x.T.readAuth());x.close();});
await test('expired resume checkpoint cannot initiate recovery',async()=>{const x=await setup({login:true});x.store.set('baka.session.test-tab',{active:true,url:'https://mooc1.chaoxing.com/mycourse/studentstudy?courseId=c&chapterId=1',at:Date.now()-86400001});assert.equal(x.T.makeAuthRequest(),null);x.close();});
await test('successful login landing returns to recorded chapter only once',async()=>{const x=await setup({login:true});const url='https://mooc1.chaoxing.com/mycourse/studentstudy?courseId=c&chapterId=109';x.store.set(authRequest,{id:'resume',owner:'test-tab',url,at:Date.now(),state:'waiting'});x.w.document.body.innerHTML='<a>我的课程</a><a>退出登录</a>';const moves=[];x.T.recoveryIO.go=u=>moves.push(u);await x.T.authTick();await x.T.authTick();assert.deepEqual(moves,[url]);x.close();});
await test('returning to original chapter restores running state and submission hold',async()=>{const x=await setup();x.T.rememberSession(true);const r=x.T.makeAuthRequest();x.store.set(authRequest,{...r,pendingSubmit:true,state:'entering',targetOwner:'test-tab'});x.T.S.started=false;await x.T.authTick();assert(x.T.S.started);assert(x.T.S.autoHold.submission);assert.equal(x.T.readAuth(),null);assert.equal(x.T.S.calls,0);x.close();});
await test('verification disappearance resumes same chapter without navigation',async()=>{const x=await setup();const b=x.w.document.createElement('div');b.id='captcha';b.textContent='请完成安全验证';x.w.document.body.append(b);const moves=[];x.T.recoveryIO.go=u=>moves.push(u);await x.T.authTick();assert.equal(x.T.S.started,false);b.remove();await x.T.authTick();assert(x.T.S.started);assert.equal(moves.length,0);x.close();});
function correctResult(x,root,answer='B'){const p=x.card.createElement('div');p.className='Py_answer';p.innerHTML='<span>正确答案：</span><span></span><span> 我的答案：A</span>';p.children[1].textContent=answer;root.append(p);return p;}
await test('bank collection is opt-in and never stores merely selected answers',async()=>{const x=await setup(),r=question(x.card,{filled:true}),b=x.w.__BANK;assert.equal(b.collectBank(true),0);correctResult(x,r);assert.equal(b.collectBank(),0);x.T.cfg.collectAnswers=true;assert.equal(b.collectBank(),1);assert.equal(b.bankEntries().length,1);assert.equal(b.bankEntries()[0].answer.choices.join(''),'B');assert.equal(b.collectBank(),0);x.close();});
await test('hidden answer and partial-credit score are not accepted as correct',async()=>{const x=await setup(),r=question(x.card,{filled:true}),b=x.w.__BANK;const p=correctResult(x,r);p.hidden=true;r.insertAdjacentHTML('beforeend','<p>得分：50 我的答案：A</p>');assert.equal(b.collectBank(true),0);x.close();});
await test('bank multi answers retain all labels and ignore student answer',async()=>{const x=await setup(),r=question(x.card,{multi:true}),b=x.w.__BANK;correctResult(x,r,'A、B、C');assert.equal(b.collectBank(true),1);assert.equal(b.bankEntries()[0].answer.choices.join(''),'ABC');x.close();});
await test('bank maps judgment words to visible choices',async()=>{const x=await setup(),r=judgeFixture(x),b=x.w.__BANK;correctResult(x,r,'错');assert.equal(b.collectBank(true),1);assert.equal(b.bankEntries()[0].answer.choices.join(''),'B');x.close();});
await test('bank remaps reordered option content and bypasses API',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;correctResult(x,r);b.collectBank(true);r.querySelector('.Py_answer').remove();const a=r.querySelectorAll('a');a[0].textContent='选项 B';a[1].textContent='选项 A';x.T.cfg.useAnswerBank=true;const answer=await x.T.answer(x.T.parseQuestion(r),x.T.currentEpoch());assert.equal(answer.choices.join(''),'A');assert.equal(x.T.S.calls,0);x.close();});
await test('bank requires identical stem and full option set',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;correctResult(x,r);b.collectBank(true);x.T.cfg.useAnswerBank=true;r.querySelector('.Zy_TItle').textContent='【单选题】测试题不正确的是';assert.equal(b.bankLookup(x.T.parseQuestion(r)),null);r.querySelector('.Zy_TItle').textContent='【单选题】测试题';r.querySelector('a').textContent='变更选项';assert.equal(b.bankLookup(x.T.parseQuestion(r)),null);x.close();});
await test('conflicting official answers are retained but never automatically reused',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;const p=correctResult(x,r);b.collectBank(true);p.children[1].textContent='C';b.collectBank(true);x.T.cfg.useAnswerBank=true;assert.equal(b.bankEntries().length,2);assert.equal(b.bankLookup(x.T.parseQuestion(r)),null);x.close();});
await test('portable export excludes credentials and unrelated settings',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;correctResult(x,r);b.collectBank(true);x.store.set(authAccounts,{'https://v8.chaoxing.com':{account:'private-user',password:'private-password'}});x.T.cfg.profiles.deepseek={key:'private-key'};const exported=b.bankExport();assert(!/private-|apiKey|password|login|https:/.test(exported));assert.deepEqual(Object.keys(JSON.parse(exported)),['format','version','entries']);x.close();});
await test('export import roundtrip merges deduplicates and labels imported provenance',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;correctResult(x,r);b.collectBank(true);const file=b.bankExport(),y=await setup(),c=y.w.__BANK;assert.equal(c.bankImport(file).added,1);assert.equal(c.bankImport(file).added,0);assert.equal(c.bankEntries()[0].source,'imported');y.T.cfg.useAnswerBank=true;assert.equal(c.bankLookup(y.T.parseQuestion(question(y.card))).choices.join(''),'B');x.close();y.close();});
await test('import is atomic when a later entry is malformed',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;correctResult(x,r);b.collectBank(true);const data=JSON.parse(b.bankExport());data.entries.push({...data.entries[0],answer:{choices:['Z'],blanks:[],answer:''}});const y=await setup();assert.throws(()=>y.w.__BANK.bankImport(JSON.stringify(data)),/不匹配/);assert.equal(y.w.__BANK.bankEntries().length,0);assert.throws(()=>b.bankImport('{broken'),/JSON/);assert.throws(()=>b.bankImport('{"format":"other","version":1,"entries":[]}'),/请选择/);x.close();y.close();});
await test('selected export contains only chosen records',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;const p=correctResult(x,r);b.collectBank(true);p.children[1].textContent='C';b.collectBank(true);assert.equal(JSON.parse(b.bankExport(new Set([b.bankEntries()[1].id]))).entries[0].answer.choices.join(''),'C');x.close();});
await test('bank collects while paused after user manually submits',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;x.T.pause();x.T.cfg.collectAnswers=true;correctResult(x,r);await x.T.recoveryTick();assert.equal(b.bankEntries().length,1);assert.equal(x.T.S.started,false);x.close();});
await test('result grace waits for delayed answer then advances without hanging',async()=>{const x=await setup({quiz:true}),r=question(x.card),b=x.w.__BANK;x.T.cfg.collectAnswers=true;x.card.body.insertAdjacentHTML('beforeend','<div class="newAnswerBx">已完成</div>');x.T.advance();assert.equal(x.counts().clicks.length,0);correctResult(x,r);x.T.S.bankWait.at-=3100;x.T.advance();assert.equal(b.bankEntries().length,1);assert.equal(x.counts().clicks.length,1);x.close();});
await test('bank pane persists toggles and selection without rendering imported HTML',async()=>{const x=await setup(),r=question(x.card),b=x.w.__BANK;correctResult(x,r);b.collectBank(true);const data=JSON.parse(b.bankExport());data.entries[0].title='<img src=x onerror=alert(1)>';b.bankImport(JSON.stringify(data));x.T.mount();const root=x.T.ui.root;root.querySelector('[data-tab="bank"]').click();assert.equal(root.querySelector('[data-pane="bank"]').hidden,false);assert.equal(root.querySelector('.bankList img'),null);assert(root.querySelector('.bankList').textContent.includes('<img'));const toggle=root.querySelector('[data-setting="collectAnswers"]');toggle.checked=true;toggle.dispatchEvent(new x.w.Event('change'));assert.equal(x.store.get('cirno.settings.v5').collectAnswers,true);root.querySelector('.bankAll').click();assert.match(root.querySelector('.bankStats').textContent,/已选 2/);x.close();});
await test('bank collects supported blank and text result formats',async()=>{for(const [title,raw,expected] of [['【填空题】补充词语','一；二','一,二'],['【简答题】说明','完整参考答案','完整参考答案']]){const x=await setup(),r=x.card.createElement('div');r.className='TiMu';r.innerHTML='<div class="Zy_TItle"></div>';r.firstChild.textContent=title;x.card.body.append(r);correctResult(x,r,raw);assert.equal(x.w.__BANK.collectBank(true),1);const a=x.w.__BANK.bankEntries()[0].answer;assert.equal(a.blanks.length?a.blanks.join(','):a.answer,expected);x.close();}});
await test('completion marker cannot skip delayed collection during submission',async()=>{const x=await setup({quiz:true}),r=question(x.card);x.T.cfg.collectAnswers=true;x.card.body.insertAdjacentHTML('beforeend','<div class="ans-job-finished"><span class="ans-job-icon" aria-label="任务点已完成"></span></div>');x.T.S.submit={d:x.card,key:x.T.pageKey(),at:Date.now()};x.T.handleSubmission();assert(x.T.S.submit);assert.equal(x.counts().clicks.length,0);correctResult(x,r);x.T.S.bankWait.at-=3100;x.T.handleSubmission();assert.equal(x.w.__BANK.bankEntries().length,1);assert.equal(x.counts().clicks.length,1);x.close();});
await test('image questions never match by text alone',async()=>{const x=await setup(),r=question(x.card);r.insertAdjacentHTML('beforeend','<svg><text>diagram</text></svg>');correctResult(x,r);x.w.__BANK.collectBank(true);x.T.cfg.useAnswerBank=true;assert.equal(x.w.__BANK.bankLookup(x.T.parseQuestion(r)),null);x.close();});
const gradedSamples=JSON.parse(fs.readFileSync(new URL('graded-fixture.json',import.meta.url),'utf8')).filter(s=>s.startsWith('<div'));
function graded(x){x.card.body.innerHTML=gradedSamples.join('\n');return x.w.__BANK;}
await test('synthetic graded result page collects all five questions including optionless judgments',async()=>{const x=await setup(),b=graded(x);assert.equal(b.collectBank(true),5);assert.deepEqual(Array.from(b.bankEntries(),e=>e.answer.choices.join('')),['A','A','A','C','ABC']);assert.equal(b.bankEntries()[0].type,'single');assert.equal(b.bankEntries()[0].options[0].text,'对');x.close();});
await test('wrong partial hidden and conflicting grading marks cannot confirm own answer',async()=>{for(const mode of ['marking_cuo','marking_bandui','hidden','conflict','missing']){const x=await setup(),b=graded(x);for(const e of x.card.querySelectorAll('.marking_dui')){if(mode==='hidden')e.hidden=true;else if(mode==='missing')e.remove();else if(mode==='conflict')e.insertAdjacentHTML('afterend','<span class="marking_bandui"></span>');else e.className=mode;}assert.equal(b.collectBank(true),0,mode);x.close();}});
await test('positive grading from a different question never leaks into another answer',async()=>{const x=await setup(),b=graded(x);x.card.querySelector('.marking_dui').remove();assert.equal(b.collectBank(true),4);assert(!b.bankEntries().some(e=>e.questionId==='700001'));x.close();});
await test('graded judgment can be reused against current true false controls',async()=>{const x=await setup(),b=graded(x);b.collectBank(true);const entry=b.bankEntries()[0];const root=judgeFixture(x),q=x.T.parseQuestion(root);q.title=entry.title;q.id=entry.questionId;q.visual=true;x.T.cfg.useAnswerBank=true;const answer=b.bankLookup(q);assert(answer);assert.equal(answer.choices.join(''),'A');x.close();});
await test('standalone scan works without API or auto collect and does not submit or play',async()=>{const x=await setup({quiz:true}),b=graded(x);const config=JSON.stringify(x.T.cfg);let submits=0;const button=x.card.createElement('button');button.textContent='提交';button.onclick=()=>submits++;x.card.body.append(button);await b.startBankScan();assert.equal(x.T.S.started,false);assert.equal(x.T.cfg.collectAnswers,false);assert.equal(JSON.stringify(x.T.cfg),config);let s=x.T.S.bankScan;s.at-=2100;await b.bankScanTick();assert.equal(s.phase,'result');s.at-=3100;await b.bankScanTick();s.stableAt-=1600;await b.bankScanTick();assert.equal(s.added,5);assert.equal(s.pages,1);assert.equal(submits,0);assert.equal(x.counts().plays,0);assert.equal(x.T.S.calls,0);b.stopBankScan();x.close();});
await test('standalone scan includes completed chapters in catalogue order',async()=>{const x=await setup({quiz:true}),b=x.w.__BANK;await b.startBankScan();const s=x.T.S.bankScan;assert.deepEqual([...s.ids],['100','101','102']);s.phase='cards';s.doneCards=['dct1','dct2'];s.at-=2100;await b.bankScanTick();await b.bankScanTick();assert.equal(s.index,1);assert.equal(x.counts().clicks.at(-1),'cur101');x.close();});
await test('scan waits for replaced card document rather than collecting stale results',async()=>{const x=await setup(),b=graded(x);await b.startBankScan();const s=x.T.S.bankScan;s.at-=2100;await b.bankScanTick();assert.equal(s.phase,'cardWait');x.w.document.querySelector('#dct1').classList.remove('active');x.w.document.querySelector('#dct2').classList.add('active');s.at-=5000;await b.bankScanTick();assert.equal(s.phase,'cardWait');assert.equal(b.bankEntries().length,0);s.at-=31000;await b.bankScanTick();assert.equal(s.phase,'cards');assert.equal(s.skipped,1);x.close();});
await test('scan stops on verification and can resume without enabling normal automation',async()=>{const x=await setup({quiz:true}),b=x.w.__BANK;await b.startBankScan();const el=x.w.document.createElement('div');el.id='captcha';el.textContent='请完成安全验证';x.w.document.body.append(el);await b.bankScanTick();assert.equal(x.T.S.bankScan.active,false);el.remove();await b.startBankScan(true);assert(x.T.S.bankScan.active);assert.equal(x.T.S.started,false);b.stopBankScan();assert.equal(x.store.get(lockKey),null);const count=x.counts().clicks.length;await x.T.recoveryTick();assert.equal(x.counts().clicks.length,count);x.close();});
await test('reload restores paused scan checkpoint and respects another page lease',async()=>{const x=await setup({quiz:true}),b=x.w.__BANK;await b.startBankScan();x.T.S.bankScan.index=1;b.stopBankScan();const saved=x.store.get('baka.bankScan.v1.test-tab');const y=await setup();y.store.set('baka.bankScan.v1.test-tab',saved);y.w.__BANK.restoreBankScan();assert.equal(y.T.S.bankScan.active,false);assert.equal(y.T.S.bankScan.index,1);y.store.set(lockKey,{owner:'other',at:Date.now()});await y.w.__BANK.startBankScan(true);assert.equal(y.T.S.bankScan.active,false);x.close();y.close();});
await test('normal start or pause cancels independent scanning',async()=>{const x=await setup({quiz:true}),b=x.w.__BANK;await b.startBankScan();await x.T.start(false,false,true);assert.equal(x.T.S.bankScan.active,false);assert(x.T.S.started);await b.startBankScan();x.T.pause();assert.equal(x.T.S.bankScan.active,false);assert.equal(x.T.S.started,false);x.close();});
console.log(`${passed} checks passed; no real API calls or live submissions.`);


